name: Build everest
on:
    workflow_dispatch:
    push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - name: Check out everest-utils
          uses: actions/checkout@v3
        #   with:
        #     repository: EVerest/everest-utils
        #     path: everest-utils
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v2
        - name: Login to Docker Hub
          uses: docker/login-action@v2
          with:
              username: ${{ secrets.DOCKERHUB_USERNAME }}
              password: ${{ secrets.DOCKERHUB_TOKEN }}
        - name: Build and push
          uses: docker/build-push-action@v4
          with:
            build-args: |
              REPO=https://github.com/EVerest/everest-core.git
              BRANCH=main
            push: true
            tags: hendry/everest:latest
        